### ISSUE TITLE
Bezier curve start point

### ISSUE THREAD

**Issue by xuezhma** [hughsk/svg-path-parser#8]
Hi,
When we are drawing a Bézier curve, it assumes the start point to be the last point in the current path. But this parser doesn't seem to be doing so. Is this something we might wanna add in the future?

**Comment by Phrogz** [comment]
@xuezhma I'm not sure that I understand what you mean by this.

Do you mean that for a path string like `M10,20 C1,2 3,4 5,6` you'd like the "3,7" added to the output for the `curveto` command?

This mostly seems like a reasonable request. A simple case involving relative commands…

```js
parse('M10,20 v10 C1,2 3,4 5,6');
[ { code:'M', command:'moveto', x:10, y:20 },
  { code:'v', command:'vertical lineto', relative:true, y:10 }, // Doesn't have x; y is actually 30
  { code:'C', command:'curveto', x1:1, y1:2, x2:3, y2:4, x:5, y:6 } ]
```

…illustrates that calculating the start point for any command potentially requires processing the entire command list up until that point.

Design thoughts:

* What would the output look like? How about for relative commands?
   * Every command has a `start` array, holding the start coordinates for the command, in absolute values (even if the command is relative).
* Do `moveto` commands include the start point?
   * No.
* How about `closepath`?
   * Yes, and also the end point (subpath start).

```js
parse('M10,20 v10 l3,4 m1,1 L20,30 L30,40z');
[ { code:'M', command:'moveto', x:10, y:20 },
  { code:'v', command:'vertical lineto', relative:true, start:[10,20], y:10 },
  { code:'l', command:'lineto', relative:true, start:[10,30], x:3, y:4 },
  { code:'m', command:'moveto', relative:true, x:1, y:1 },
  { code:'L', command:'lineto', start:[11,31], x:20, y:30 },
  { code:'L', command:'lineto', start:[20,30], x:30, y:40 },
  { code:'Z', command:'closepath', start:[30,40], end:[11,31] } ]
```

If implemented like this, would it solve your needs?

**Comment by Phrogz** [comment]
Here's a modified version of the parser that accomplishes the above:

```js
svg_path
  = wsp* data:moveTo_drawTo_commandGroups? wsp*
  {
    for (var cmds=[],i=0;i<data.length;i++) cmds=cmds.concat.apply(cmds,data[i]);
    var first=cmds[0];
    if (first && first.code=='m'){ // Per spec, first moveto is never relative
      delete first.relative;
      first.code = 'M';
    }
    // Carry `start` (and `end`) properties along
    var lastX, lastY, subX, subY;
    for (var i=0;i<cmds.length;++i){
      var cmd = cmds[i], isMove = (cmd.code.toLowerCase()=='m');
      if (lastX!==undefined && !isMove){
        cmd.start = [lastX,lastY];
      }
      if ('x' in cmd){
        lastX = (cmd.relative ? lastX : 0) + cmd.x;
        if (isMove) subX=lastX;
      }
      if ('y' in cmd){
        lastY = (cmd.relative ? lastY : 0) + cmd.y;
        if (isMove) subY=lastY;
      }
      if (cmd.code.toLowerCase()=='z') cmd.end=[subX,subY];
    }
    return cmds;
  }
```

**Comment by xuezhma** [comment]
@Phrogz thanks for following up.

> parse('M10,20 v10 l3,4 m1,1 L20,30 L30,40z');
[ { code:'M', command:'moveto', x:10, y:20 },
  { code:'v', command:'vertical lineto', relative:true, start:[10,20], y:10 },
  { code:'l', command:'lineto', relative:true, start:[10,30], x:3, y:4 },
  { code:'m', command:'moveto', relative:true, x:1, y:1 },
  { code:'L', command:'lineto', start:[14,35], x:20, y:30 },
  { code:'L', command:'lineto', start:[20,30], x:30, y:40 },
  { code:'Z', command:'closepath', start:[30,40], end:[14,35] } ]


this is exactly what I would have loved to have. Our problem was solved, doing something similar, adding the start points as x0 y0.

**Comment by Phrogz** [comment]
This is (finally) implemented by the optional `makeAbsolute()` function added in v1.1
